export const FASHION_BRANDS: string[] = [
  "A.P.C.",
  "Abercrombie & Fitch",
  "Acne Studios",
  "Adidas",
  "Agent Provocateur",
  "Alexander McQueen",
  "Alexander Wang",
  "Alice + Olivia",
  "AllSaints",
  "Allbirds",
  "Alo Yoga",
  "American Eagle",
  "American Giant",
  "American Rag",
  "Ann Taylor",
  "Anthropologie",
  "Arc'teryx",
  "Aritzia",
  "Armani Exchange",
  "ASOS",
  "Athleta",
  "Balenciaga",
  "Banana Republic",
  "BCBGMaxAzria",
  "Bershka",
  "Birkenstock",
  "Bottega Veneta",
  "Brooks Brothers",
  "Brooks Running",
  "Brunello Cucinelli",
  "Burberry",
  "Calvin Klein",
  "Canada Goose",
  "Carhartt",
  "Champion",
  "Charles & Keith",
  "Chloé",
  "Citizens of Humanity",
  "Club Monaco",
  "Coach",
  "Columbia",
  "Comme des Garçons",
  "COS",
  "Cotton On",
  "Courreges",
  "Current/Elliott",
  "David Yurman",
  "Derek Lam",
  "Diane von Furstenberg",
  "Dior",
  "DKNY",
  "Dr. Martens",
  "Dsquared2",
  "Eileen Fisher",
  "Equipment",
  "Everlane",
  "Express",
  "Faherty",
  "Fendi",
  "Fjällräven",
  "Frame",
  "Free People",
  "French Connection",
  "G-Star Raw",
  "Gap",
  "Ganni",
  "Giorgio Armani",
  "Givenchy",
  "Golden Goose",
  "Good American",
  "Grail",
  "Gucci",
  "Guess",
  "H&M",
  "Hanes",
  "Helmut Lang",
  "Hermès",
  "Highline Collective",
  "HOKA",
  "Hugo Boss",
  "Icebreaker",
  "Isabel Marant",
  "J. Crew",
  "Jack & Jones",
  "Jacquemus",
  "James Perse",
  "Joe's Jeans",
  "John Varvatos",
  "Johnny Was",
  "Kate Spade",
  "Kenneth Cole",
  "Kenzo",
  "Kit and Ace",
  "Lacoste",
  "Lane Bryant",
  "Levi's",
  "Loewe",
  "Louis Vuitton",
  "Lucky Brand",
  "Lululemon",
  "Madewell",
  "Maison Margiela",
  "Marc Jacobs",
  "Marine Serre",
  "Max Mara",
  "Michael Kors",
  "Miu Miu",
  "MM LaFleur",
  "Moncler",
  "Monki",
  "Moschino",
  "Muji",
  "Nanushka",
  "New Balance",
  "New Era",
  "Nike",
  "Nudie Jeans",
  "Off-White",
  "Old Navy",
  "Oliver Spencer",
  "On Running",
  "Opening Ceremony",
  "Original Penguin",
  "Outdoor Voices",
  "Paige",
  "Palm Angels",
  "Patagonia",
  "Paul Smith",
  "Polo Ralph Lauren",
  "Prada",
  "Puma",
  "Rag & Bone",
  "Ralph Lauren",
  "Recess",
  "Reebok",
  "Reformation",
  "Represent",
  "Rick Owens",
  "River Island",
  "Roots",
  "Sacai",
  "Saint Laurent",
  "Sandro",
  "Scotch & Soda",
  "Skechers",
  "Solid & Striped",
  "Splendid",
  "Stella McCartney",
  "Stone Island",
  "Supreme",
  "Sweaty Betty",
  "Ted Baker",
  "The North Face",
  "Theory",
  "Thom Browne",
  "Tiger of Sweden",
  "Todd Snyder",
  "Tom Ford",
  "Tommy Hilfiger",
  "Tory Burch",
  "Toteme",
  "True Religion",
  "UGG",
  "Under Armour",
  "Uniqlo",
  "Valentino",
  "Van Heusen",
  "Vans",
  "Versace",
  "Victoria Beckham",
  "Victoria's Secret",
  "Vuori",
  "Wrangler",
  "Zara",
  "Zimmermann",
  // Additional brands to reach ~300
  "3.1 Phillip Lim",
  "7 For All Mankind",
  "Aeropostale",
  "Aeyde",
  "Agnes B",
  "Aime Leon Dore",
  "AJ Tracey",
  "Aje",
  "Alaia",
  "Alder Apparel",
  "Alex Mill",
  "Alexis",
  "AllSaints",
  "Alpha Industries",
  "Altuzarra",
  "Ancient Greek Sandals",
  "Andrew Marc",
  "Ann Demeulemeester",
  "Anine Bing",
  "Another Tomorrow",
  "Anrealage",
  "Arket",
  "Asics",
  "Aster",
  "Baldinini",
  "Barbour",
  "Bally",
  "Bassike",
  "Baukjen",
  "Bec & Bridge",
  "Bella Dahl",
  "Belstaff",
  "Bimba Y Lola",
  "Blazé Milano",
  "Bonobos",
  "Boss",
  "Bottega Veneta",
  "Bruno Cucinelli",
  "Bvlgari",
  "By Malene Birger",
  "Camper",
  "Casablanca",
  "Catbird",
  "Celine",
  "Charlotte Tilbury",
  "Chanel",
  "Chelsea Peers",
  "Christian Louboutin",
  "Cinq a Sept",
  "Clarks",
  "Claudie Pierlot",
  "Closed",
  "Co",
  "Cole Haan",
  "Commense",
  "Converse",
  "Coperni",
  "Cos",
  "Cult Gaia",
  "Cuyana",
  "Dagne Dover",
  "Denim Forum",
  "Derek Rose",
  "Desigual",
  "Dôen",
  "Dolce & Gabbana",
  "Dries Van Noten",
  "Dunhill",
  "Elie Saab",
  "Emilio Pucci",
  "Erdem",
  "Erin Snow",
  "Erring",
  "Etoile Isabel Marant",
  "EXS",
  "Fila",
  "Fleur du Mal",
  "Florentina Leitner",
  "Fossil",
  "Foundrae",
  "Frank & Oak",
  "Frye",
  "Giuliva Heritage",
  "Goop",
  "Gosha Rubchinskiy",
  "Grenson",
  "Ganni",
  "H Fredriksson",
  "Hackett",
  "Harris Wharf London",
  "Hazel Brown",
  "Herno",
  "Herschel",
  "Hobbs",
  "House of CB",
  "Hunza G",
  "Hyke",
  "Iro",
  "J.W. Anderson",
  "Jacadi",
  "Jil Sander",
  "Jimmy Choo",
  "Jonathan Simkhai",
  "Joseph",
  "Julien David",
  "Kassl Editions",
  "Khaite",
  "Kitri",
  "Kotn",
  "Loro Piana",
  "Louis & Mia",
  "Loveshackfancy",
  "Lunya",
  "Mango",
  "Margaret Howell",
  "Massimo Dutti",
  "Matteau",
  "Matthew Adams Dolan",
  "Max & Moi",
  "Me+Em",
  "Meredith Wendell",
  "Miaou",
  "Milk Makeup",
  "Mirae",
  "Missoni",
  "Monse",
  "Morphew",
  "Mossimo",
  "Mother Denim",
  "MZ Wallace",
  "Nanette Lepore",
  "Needles",
  "Net-a-Porter",
  "Nicole Miller",
  "Nine West",
  "Nili Lotan",
  "Norma Kamali",
  "Norse Projects",
  "Officine Generale",
  "Paloma Wool",
  "Pangaia",
  "Paper London",
  "Partow",
  "Perks and Mini",
  "Peter Do",
  "Peter Millar",
  "Pixie Market",
  "Pleats Please",
  "Proenza Schouler",
  "Pull & Bear",
  "Quince",
  "Rachel Comey",
  "Rains",
  "Rebecca Minkoff",
  "Rebecca Taylor",
  "Reiss",
  "Roarke",
  "Robert Rodriguez",
  "Roland Mouret",
  "Rosie Assoulin",
  "Rotate Birger Christensen",
  "Rothy's",
  "Rue Stiic",
  "Salehe Bembury",
  "Salomon",
  "Sanctuary",
  "Sergio Rossi",
  "Sessun",
  "Simone Rocha",
  "Sita Murt",
  "Skims",
  "Slvrlake",
  "Snow Peak",
  "Soeur",
  "Sofie D'Hoore",
  "Something Navy",
  "Spanx",
  "St. John",
  "Staud",
  "Stelen",
  "Steven Alan",
  "Storet",
  "Stussy",
  "Sunflower",
  "Suq",
  "Telfar",
  "The Frankie Shop",
  "The Row",
  "Tibi",
  "Tiimo",
  "Toit Volant",
  "Topman",
  "Toteme",
  "Trademark",
  "Veja",
  "Veronica Beard",
  "Vetements",
  "Viktor & Rolf",
  "Vince",
  "Vivienne Westwood",
  "Wales Bonner",
  "Warby Parker",
  "Weekday",
  "White House Black Market",
  "Wolford",
  "Y-3",
  "Yeezy",
  "Yohji Yamamoto",
  "Zac Posen",
].filter((v, i, a) => a.findIndex(b => b.toLowerCase() === v.toLowerCase()) === i)
 .sort((a, b) => a.localeCompare(b));
